spring.application.name=cabinet-kine-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/cabinet_kine
spring.datasource.username=postgres
spring.datasource.password=2528
spring.jpa.hibernate.ddl-auto=update
